### ISSUE TITLE
Runtime Error : Detected problem with app native libraries

### ISSUE THREAD

**Issue by BossIsBack007** [Zod20/OpenCV-Face-Recognition-Android#1]
Whenever I clicked on Train or recognition then app will stop with following Error.

Detected problem with app native libraries
![img_20180129_171149](https://user-images.githubusercontent.com/35921780/35510061-8f007450-051c-11e8-9993-6880043d9a3a.jpg)

**Comment by Zod20** [comment]
Hmm it seems like a permission issue. This app was developed over 2 years ago when the permission system for the Android OS was much more lenient. Also the NDK was a mess back then.

I would suggest making a new project in Android Studio and add JavaCV dependencies in Gradle.

```
// https://mvnrepository.com/artifact/org.bytedeco/javacv
compile group: 'org.bytedeco', name: 'javacv', version: '1.3.1'
```
Then take out some of the core classes from my project and implement then one at a time until you see what breaks and make fixes accordingly. This will upgrade the whole project to run on current systems with proper permissions etc. Hope that helps!

**Comment by BossIsBack007** [comment]
I added newer library but there are little older code exist in your project ... 
so it shows following errors.

function name in **Bold** style is error.

1.
bool = opencv_highgui.**imwrite**(filename, MatFace);

2.
 Mat outputImage = opencv_highgui.**imdecode**(new Mat(temporaryImageInMemory), opencv_highgui.**IMREAD_GRAYSCALE**);


I want to know which method is used for it.
or alternative way to resolve it.

**Comment by Zod20** [comment]
There's actually a newer version of JavaCV out - 1.4 so I recommend using that in Gradle.

 ```
dependencies {
    compile group: 'org.bytedeco', name: 'javacv-platform', version: '1.4'
  }
```

You can find more information on JavaCV as well as some very good sample programs from the official JavaCV github page - []https://github.com/bytedeco/javacv

Check if you can find **imread** & **imwrite** functions inside opencv_imgcodecs.

So replace - 
`bool = opencv_highgui.imwrite(filename, MatFace);`
with
`bool = opencv_imgcodecs.imwrite(filename, MatFace);`
